version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      java-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/frontend/app"
    schedule:
      interval: "weekly"
    groups:
      frontend-dependencies:
        patterns:
          - "*"
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
