/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenantId}/loan-origination/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/loan-origination/valuation-guidelines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGuidelines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateLoanRequest: {
            customerId: string;
            positions?: components["schemas"]["PositionPayload"][];
            /** Format: int32 */
            termMonths?: number;
            manualMonthlyOperatingFee?: number;
            thirdPartyPledgorPresentation?: boolean;
            bearerName?: string;
            bearerStreet?: string;
            bearerPostalCode?: string;
            bearerCity?: string;
            powerOfAttorneyDocumentDataUrl?: string;
        };
        PositionPayload: {
            /** Format: int32 */
            ticketGroup: number;
            label: string;
            description: string;
            guidelineId: string;
            pledgedValue?: number;
        };
        CustomerView: {
            id?: string;
            customerNumber?: string;
            displayName?: string;
            /** Format: date */
            birthDate?: string;
            phone?: string;
            checkedDocumentType?: string;
        };
        LoanCaseResponse: {
            id?: string;
            customer?: components["schemas"]["CustomerView"];
            pledgeRecord?: components["schemas"]["PledgeRecordResponse"];
            positions?: components["schemas"]["LoanPositionResponse"][];
            pawnTickets?: components["schemas"]["PawnTicketResponse"][];
        };
        LoanPositionResponse: {
            id?: string;
            /** Format: int32 */
            ticketGroup?: number;
            label?: string;
            description?: string;
            guidelineLabel?: string;
            baseLoanValue?: number;
            pledgedValue?: number;
        };
        PawnTicketPositionResponse: {
            itemNumber?: string;
            itemBarcode?: string;
            label?: string;
            description?: string;
            pledgedValue?: number;
        };
        PawnTicketResponse: {
            contractNumber?: string;
            contractBarcode?: string;
            ticketNumber?: string;
            termsVersion?: string;
            termsAndConditionsText?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date */
            dueDate?: string;
            /** Format: date */
            earliestAuctionDate?: string;
            /** Format: int32 */
            termMonths?: number;
            totalLoanValue?: number;
            monthlyInterestRate?: number;
            monthlyOperatingFee?: number;
            manualMonthlyOperatingFeeRequired?: boolean;
            totalInterestAmount?: number;
            totalOperatingFeeAmount?: number;
            totalRepaymentAmount?: number;
            legalText?: string;
            positions?: components["schemas"]["PawnTicketPositionResponse"][];
        };
        PledgeRecordResponse: {
            id?: string;
            /** Format: date-time */
            recordedAt?: string;
            languageCode?: string;
            /** Format: date */
            retentionUntil?: string;
            pledgorName?: string;
            pledgorStreet?: string;
            pledgorPostalCode?: string;
            pledgorCity?: string;
            /** Format: date */
            pledgorBirthDate?: string;
            checkedDocumentType?: string;
            powerOfAttorneyRequired?: boolean;
            bearerName?: string;
            bearerStreet?: string;
            bearerPostalCode?: string;
            bearerCity?: string;
        };
        ValuationGuidelineResponse: {
            id?: string;
            category?: string;
            material?: string;
            label?: string;
            description?: string;
            baseLoanValue?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: {
                customerId?: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanCaseResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLoanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoanCaseResponse"];
                };
            };
        };
    };
    listGuidelines: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ValuationGuidelineResponse"][];
                };
            };
        };
    };
}
