/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenantId}/reporting/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        FinanceSummaryResponse: {
            cashInflow?: number;
            cashOutflow?: number;
            netCashflow?: number;
            realizedRevenue?: number;
            activeLoanExposure?: number;
            /** Format: int32 */
            activeTicketCount?: number;
            averageTicketValue?: number;
        };
        FinanceTrendPointResponse: {
            /** Format: date */
            date?: string;
            cashInflow?: number;
            cashOutflow?: number;
            realizedRevenue?: number;
        };
        InventoryCategoryResponse: {
            category?: string;
            /** Format: int32 */
            itemCount?: number;
            pledgedValue?: number;
        };
        ReportingDashboardResponse: {
            /** Format: date */
            rangeStart?: string;
            /** Format: date */
            rangeEnd?: string;
            /** Format: date-time */
            generatedAt?: string;
            finance?: components["schemas"]["FinanceSummaryResponse"];
            financeTrend?: components["schemas"]["FinanceTrendPointResponse"][];
            inventoryByCategory?: components["schemas"]["InventoryCategoryResponse"][];
            transactionMix?: components["schemas"]["TransactionMixResponse"][];
        };
        TransactionMixResponse: {
            type?: string;
            /** Format: int32 */
            transactionCount?: number;
            totalAmount?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    dashboard: {
        parameters: {
            query?: {
                rangeDays?: number;
            };
            header: {
                Authorization: string;
            };
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportingDashboardResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
