/*
 * Lombardio Source-Available No-Distribution License 1.0
 *
 * Copyright (c) 2026 Benjamin Letzel. All rights reserved.
 *
 * This project is source-available for educational and review purposes only.
 * Redistribution, sublicensing, or commercial use is strictly prohibited.
 *
 * For partnership or cooperation inquiries, please contact the author.
 */
package io.lombardio.loanorigination.api.http.mapper;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.lombardio.loanorigination.api.http.CreateLoanRequest;
import io.lombardio.loanorigination.api.http.CustomerView;
import io.lombardio.loanorigination.api.http.LoanCaseResponse;
import io.lombardio.loanorigination.api.http.LoanPositionResponse;
import io.lombardio.loanorigination.api.http.PawnTicketPositionResponse;
import io.lombardio.loanorigination.api.http.PawnTicketResponse;
import io.lombardio.loanorigination.api.http.PledgeRecordResponse;
import io.lombardio.loanorigination.api.http.PositionPayload;
import io.lombardio.loanorigination.api.http.ValuationGuidelineResponse;
import io.lombardio.loanorigination.application.service.CreateLoanCommand;
import io.lombardio.loanorigination.application.service.CreateLoanPositionCommand;
import io.lombardio.loanorigination.domain.model.CustomerProfile;
import io.lombardio.loanorigination.domain.model.LoanCase;
import io.lombardio.loanorigination.domain.model.LoanPosition;
import io.lombardio.loanorigination.domain.model.PawnTicket;
import io.lombardio.loanorigination.domain.model.PawnTicketPosition;
import io.lombardio.loanorigination.domain.model.PledgeRecord;
import io.lombardio.loanorigination.domain.model.ValuationGuideline;
import org.mapstruct.Mapper;

@Mapper(componentModel = "spring")
@SuppressFBWarnings(value = "NP_LOAD_OF_KNOWN_NULL_VALUE", justification = "Generated by MapStruct")
public interface ApiMapper {

  LoanCaseResponse toResponse(LoanCase domain);

  PledgeRecordResponse toResponse(PledgeRecord domain);

  LoanPositionResponse toResponse(LoanPosition domain);

  PawnTicketResponse toResponse(PawnTicket domain);

  PawnTicketPositionResponse toResponse(PawnTicketPosition domain);

  ValuationGuidelineResponse toResponse(ValuationGuideline domain);

  CustomerView toView(CustomerProfile domain);

  CreateLoanCommand toCommand(CreateLoanRequest request);

  CreateLoanPositionCommand toPositionCommand(PositionPayload payload);
}
