/*
 * Lombardio Source-Available No-Distribution License 1.0
 *
 * Copyright (c) 2026 Benjamin Letzel. All rights reserved.
 *
 * This project is source-available for educational and review purposes only.
 * Redistribution, sublicensing, or commercial use is strictly prohibited.
 *
 * For partnership or cooperation inquiries, please contact the author.
 */
package io.lombardio.loanorigination.infrastructure.persistence.mapper;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import io.lombardio.loanorigination.domain.model.CustomerProfile;
import io.lombardio.loanorigination.domain.model.LoanCase;
import io.lombardio.loanorigination.domain.model.LoanPosition;
import io.lombardio.loanorigination.domain.model.PawnTicket;
import io.lombardio.loanorigination.domain.model.PawnTicketPosition;
import io.lombardio.loanorigination.domain.model.PledgeRecord;
import io.lombardio.loanorigination.domain.model.ValuationGuideline;
import io.lombardio.loanorigination.infrastructure.persistence.entity.LoanCaseEntity;
import io.lombardio.loanorigination.infrastructure.persistence.entity.LoanPawnTicketEntity;
import io.lombardio.loanorigination.infrastructure.persistence.entity.LoanPositionEntity;
import io.lombardio.loanorigination.infrastructure.persistence.entity.PledgeRecordEntity;
import io.lombardio.loanorigination.infrastructure.persistence.entity.ValuationGuidelineEntity;
import java.util.List;
import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = "spring")
@SuppressFBWarnings(value = "NP_LOAD_OF_KNOWN_NULL_VALUE", justification = "Generated by MapStruct")
public interface PersistenceMapper {

  // LoanCase mapping
  @Mapping(target = "pledgeRecords", ignore = true)
  @Mapping(target = "positions", ignore = true)
  @Mapping(target = "pawnTickets", ignore = true)
  @Mapping(target = "customerId", source = "customer.id")
  @Mapping(target = "customerNumber", source = "customer.customerNumber")
  @Mapping(target = "customerDisplayName", source = "customer.displayName")
  @Mapping(target = "customerBirthDate", source = "customer.birthDate")
  @Mapping(target = "customerPhone", source = "customer.phone")
  @Mapping(target = "customerStreet", source = "customer.street")
  @Mapping(target = "customerPostalCode", source = "customer.postalCode")
  @Mapping(target = "customerCity", source = "customer.city")
  @Mapping(target = "customerKycStatus", source = "customer.kycStatus")
  @Mapping(target = "customerKycApproved", source = "customer.kycApproved")
  @Mapping(target = "customerCheckedDocumentType", source = "customer.checkedDocumentType")
  LoanCaseEntity toEntity(LoanCase domain);

  @Mapping(target = "customer", source = "entity")
  @Mapping(
      target = "pledgeRecord",
      expression =
          "java(entity.getPledgeRecords().isEmpty() ? null : toDomain(entity.getPledgeRecords().get(0)))")
  LoanCase toDomain(LoanCaseEntity entity);

  @Mapping(target = "id", source = "customerId")
  @Mapping(target = "customerNumber", source = "customerNumber")
  @Mapping(target = "displayName", source = "customerDisplayName")
  @Mapping(target = "birthDate", source = "customerBirthDate")
  @Mapping(target = "phone", source = "customerPhone")
  @Mapping(target = "street", source = "customerStreet")
  @Mapping(target = "postalCode", source = "customerPostalCode")
  @Mapping(target = "city", source = "customerCity")
  @Mapping(target = "kycStatus", source = "customerKycStatus")
  @Mapping(target = "kycApproved", source = "customerKycApproved")
  @Mapping(target = "checkedDocumentType", source = "customerCheckedDocumentType")
  CustomerProfile toCustomerProfile(LoanCaseEntity entity);

  // PledgeRecord mapping
  @Mapping(target = "loanCase", ignore = true)
  @Mapping(target = "sortOrder", ignore = true)
  PledgeRecordEntity toEntity(PledgeRecord domain);

  @Mapping(target = "loanCaseId", source = "loanCase.id")
  PledgeRecord toDomain(PledgeRecordEntity entity);

  // LoanPosition mapping
  @Mapping(target = "id", expression = "java(java.util.UUID.randomUUID().toString())")
  @Mapping(target = "loanCase", ignore = true)
  @Mapping(target = "sortOrder", ignore = true)
  LoanPositionEntity toEntity(LoanPosition domain);

  LoanPosition toDomain(LoanPositionEntity entity);

  // PawnTicket mapping
  @Mapping(target = "loanCase", ignore = true)
  @Mapping(target = "sortOrder", ignore = true)
  LoanPawnTicketEntity toEntity(PawnTicket domain);

  @Mapping(target = "positions", source = "loanCase.positions")
  PawnTicket toDomain(LoanPawnTicketEntity entity);

  // Position mapping
  @Mapping(target = "itemNumber", source = "ticketGroup")
  @Mapping(target = "itemBarcode", source = "id")
  PawnTicketPosition toPositionDomain(LoanPositionEntity entity);

  // ValuationGuideline mapping
  ValuationGuidelineEntity toEntity(ValuationGuideline domain);

  ValuationGuideline toDomain(ValuationGuidelineEntity entity);

  @AfterMapping
  default void linkEntities(@MappingTarget LoanCaseEntity entity, LoanCase domain) {
    if (domain.pledgeRecord() != null) {
      PledgeRecordEntity recordEntity = toEntity(domain.pledgeRecord());
      recordEntity.setLoanCase(entity);
      recordEntity.setSortOrder(0);
      entity.getPledgeRecords().add(recordEntity);
    }
    if (domain.positions() != null) {
      List<LoanPosition> positions = domain.positions();
      for (int i = 0; i < positions.size(); i++) {
        LoanPositionEntity posEntity = toEntity(positions.get(i));
        posEntity.setLoanCase(entity);
        posEntity.setSortOrder(i);
        entity.getPositions().add(posEntity);
      }
    }
    if (domain.pawnTickets() != null) {
      List<PawnTicket> tickets = domain.pawnTickets();
      for (int i = 0; i < tickets.size(); i++) {
        LoanPawnTicketEntity ticketEntity = toEntity(tickets.get(i));
        ticketEntity.setLoanCase(entity);
        ticketEntity.setSortOrder(i);
        entity.getPawnTickets().add(ticketEntity);
      }
    }
  }
}
