/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenantId}/customers/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getById"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/kyc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus"];
        put?: never;
        post: operations["updateStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/kyc/document-prefill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["prefillDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/aml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStatus_1"];
        put?: never;
        post: operations["updateStatus_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/aml/origination-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["assessForOrigination"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/invitations/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["invitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/kyc/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/kyc/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["approval"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/customers/{customerId}/aml/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/pawn-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pawnTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/pawn-tickets/{ticketNumber}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer-portal/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateCustomerRequest: {
            customerNumber: string;
            firstName: string;
            lastName: string;
            /** Format: date */
            birthDate: string;
            phone: string;
            email?: string;
            wantsDigitalPawnTicket?: boolean;
            street?: string;
            postalCode?: string;
            city?: string;
        };
        CustomerView: {
            id: string;
            customerNumber: string;
            firstName: string;
            lastName: string;
            /** Format: date */
            birthDate: string;
            displayName: string;
            phone: string;
            email: string;
            wantsDigitalPawnTicket: boolean;
            onlineAccessStatus: string;
            kycStatus: string;
            kycApproved: boolean;
            kycDocumentType: string;
            street: string;
            postalCode: string;
            city: string;
        };
        CreateCustomerRequest: {
            customerNumber: string;
            firstName: string;
            lastName: string;
            /** Format: date */
            birthDate: string;
            phone: string;
            email?: string;
            wantsDigitalPawnTicket?: boolean;
            street?: string;
            postalCode?: string;
            city?: string;
        };
        UpdateKycStatusRequest: {
            /** @enum {string} */
            status: UpdateKycStatusRequestStatus;
            /** @enum {string} */
            verificationMode?: UpdateKycStatusRequestVerificationMode;
            /** Format: date */
            verifiedUntil?: string;
            documentType?: string;
            documentNumber?: string;
            /** Format: date */
            documentValidUntil?: string;
            documentFrontImageDataUrl?: string;
            documentBackImageDataUrl?: string;
            decisionNote?: string;
            providerName?: string;
            providerReference?: string;
            providerStatus?: string;
        };
        KycStatusView: {
            customerId: string;
            /** @enum {string} */
            verificationMode: KycStatusViewVerificationMode;
            /** @enum {string} */
            status: KycStatusViewStatus;
            /** Format: date */
            verifiedUntil: string;
            documentType: string;
            documentNumber: string;
            /** Format: date */
            documentValidUntil: string;
            decisionNote: string;
            providerName: string;
            providerReference: string;
            providerStatus: string;
            providerVerificationAvailable: boolean;
        };
        DocumentPrefillRequest: {
            documentFrontImageDataUrl: string;
            documentBackImageDataUrl?: string;
        };
        DocumentPrefillView: {
            available: boolean;
            matched: boolean;
            firstName: string;
            lastName: string;
            /** Format: date */
            birthDate: string;
            documentType: string;
            documentNumber: string;
            /** Format: date */
            documentValidUntil: string;
            portraitImageDataUrl: string;
            providerName: string;
            /** Format: double */
            confidence: number;
        };
        UpdateAmlStatusRequest: {
            /** @enum {string} */
            status: UpdateAmlStatusRequestStatus;
            /** @enum {string} */
            riskLevel: UpdateAmlStatusRequestRiskLevel;
            pepFlag?: boolean;
            sanctionsHit?: boolean;
            unusualTransactionFlag?: boolean;
            sourceOfFundsChecked?: boolean;
            suspiciousActivityReported?: boolean;
            goamlReference?: string;
            decisionNote?: string;
            /** Format: date-time */
            lastScreenedAt?: string;
            /** Format: date-time */
            reviewedAt?: string;
        };
        AmlStatusView: {
            customerId: string;
            /** @enum {string} */
            status: AmlStatusViewStatus;
            /** @enum {string} */
            riskLevel: AmlStatusViewRiskLevel;
            pepFlag: boolean;
            sanctionsHit: boolean;
            unusualTransactionFlag: boolean;
            sourceOfFundsChecked: boolean;
            suspiciousActivityReported: boolean;
            goamlReference: string;
            decisionNote: string;
            /** Format: date-time */
            lastScreenedAt: string;
            /** Format: date-time */
            reviewedAt: string;
            featureAvailable: boolean;
            originationAllowed: boolean;
            decisionReason: string;
        };
        OriginationAssessmentRequest: {
            loanAmount: number;
        };
        CustomerPortalInvitationLookupRequest: {
            token: string;
        };
        CustomerPortalInvitationView: {
            customerDisplayName: string;
            email: string;
            status: string;
        };
        CustomerPortalAcceptInvitationRequest: {
            token: string;
            password: string;
        };
        CustomerPortalCustomerView: {
            customerId: string;
            tenantId: string;
            displayName: string;
            email: string;
            onlineAccessStatus: string;
        };
        CustomerPortalLoginView: {
            accessToken: string;
            customer: components["schemas"]["CustomerPortalCustomerView"];
        };
        CustomerPortalLoginRequest: {
            email: string;
            password: string;
        };
        KycDocumentImagesView: {
            customerId: string;
            documentFrontImageDataUrl: string;
            documentBackImageDataUrl: string;
        };
        CustomerPortalPawnTicketView: {
            contractNumber: string;
            ticketNumber: string;
            contractBarcode: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date */
            dueDate: string;
            /** Format: date */
            earliestAuctionDate: string;
            loanAmount: number;
            totalRepaymentAmount: number;
            /** Format: int32 */
            positionCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerView"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KycStatusView"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateKycStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KycStatusView"];
                };
            };
        };
    };
    prefillDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentPrefillRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentPrefillView"];
                };
            };
        };
    };
    getStatus_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AmlStatusView"];
                };
            };
        };
    };
    updateStatus_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAmlStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AmlStatusView"];
                };
            };
        };
    };
    assessForOrigination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OriginationAssessmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AmlStatusView"];
                };
            };
        };
    };
    invitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPortalInvitationLookupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerPortalInvitationView"];
                };
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPortalAcceptInvitationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerPortalLoginView"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerPortalLoginView"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerPortalLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerPortalLoginView"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["KycDocumentImagesView"];
                };
            };
        };
    };
    approval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    health_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    pawnTickets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerPortalPawnTicketView"][];
                };
            };
        };
    };
    document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerPortalCustomerView"];
                };
            };
        };
    };
}
export enum UpdateKycStatusRequestStatus {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}
export enum UpdateKycStatusRequestVerificationMode {
    MANUAL = "MANUAL",
    PROVIDER = "PROVIDER"
}
export enum KycStatusViewVerificationMode {
    MANUAL = "MANUAL",
    PROVIDER = "PROVIDER"
}
export enum KycStatusViewStatus {
    NOT_STARTED = "NOT_STARTED",
    IN_PROGRESS = "IN_PROGRESS",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}
export enum UpdateAmlStatusRequestStatus {
    NOT_REVIEWED = "NOT_REVIEWED",
    CLEAR = "CLEAR",
    REVIEW_REQUIRED = "REVIEW_REQUIRED",
    BLOCKED = "BLOCKED",
    REPORTED = "REPORTED"
}
export enum UpdateAmlStatusRequestRiskLevel {
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH"
}
export enum AmlStatusViewStatus {
    NOT_REVIEWED = "NOT_REVIEWED",
    CLEAR = "CLEAR",
    REVIEW_REQUIRED = "REVIEW_REQUIRED",
    BLOCKED = "BLOCKED",
    REPORTED = "REPORTED"
}
export enum AmlStatusViewRiskLevel {
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH = "HIGH"
}
