/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenantId}/online-auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/online-auctions/{auctionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/online-auctions/{auctionId}/registrations/{registrationId}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reviewRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/online-auctions/{auctionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/online-auctions/{auctionId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/tenants/{tenantId}/online-auctions/{auctionId}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/tenants/{tenantId}/online-auctions/{auctionId}/realtime-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueRealtimeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/tenants/{tenantId}/online-auctions/{auctionId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/tenants/{tenantId}/online-auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/tenants/{tenantId}/online-auctions/{auctionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOnlineAuctionRequest: {
            title: string;
            slug: string;
            minimumIncrement: number;
            /** Format: int32 */
            countdownSeconds?: number;
            lots?: components["schemas"]["OnlineAuctionLotRequest"][];
        };
        OnlineAuctionLotRequest: {
            title: string;
            description: string;
            startingBid: number;
        };
        BidderRegistrationResponse: {
            id: string;
            displayName: string;
            email: string;
            legalName: string;
            birthDate: string;
            ibanMasked: string;
            paddleNumber: string;
            accessToken: string;
            /** @enum {string} */
            approvalStatus: BidderRegistrationResponseApprovalStatus;
            /** @enum {string} */
            kycStatus: BidderRegistrationResponseKycStatus;
            /** @enum {string} */
            accountCheckStatus: BidderRegistrationResponseAccountCheckStatus;
            reviewNote: string;
            /** Format: date-time */
            approvedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        OnlineAuctionLotResponse: {
            id: string;
            /** Format: int32 */
            lotNumber: number;
            title: string;
            description: string;
            startingBid: number;
            currentBid: number;
            highestBidderAlias: string;
        };
        OnlineAuctionResponse: {
            id: string;
            tenantId: string;
            title: string;
            slug: string;
            /** @enum {string} */
            status: OnlineAuctionResponseStatus;
            channelName: string;
            minimumIncrement: number;
            /** Format: int32 */
            countdownSeconds: number;
            /** Format: date-time */
            publishedAt: string;
            /** Format: date-time */
            liveStartedAt: string;
            /** Format: date-time */
            countdownEndsAt: string;
            /** Format: date-time */
            closedAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            lots: components["schemas"]["OnlineAuctionLotResponse"][];
            registrations: components["schemas"]["BidderRegistrationResponse"][];
        };
        BidderReviewRequest: {
            kycStatus: string;
            accountCheckStatus: string;
            decision: string;
            reviewNote?: string;
        };
        RegisterBidderRequest: {
            displayName: string;
            email: string;
            legalName: string;
            birthDate: string;
            iban: string;
        };
        RealtimeSessionRequest: {
            accessToken: string;
        };
        RealtimeSessionResponse: {
            wsUrl: string;
            channel: string;
            connectionToken: string;
            subscriptionToken: string;
        };
        PlaceOnlineBidRequest: {
            accessToken: string;
            lotId: string;
            amount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOnlineAuctionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
    reviewRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
                registrationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BidderReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
    close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBidderRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BidderRegistrationResponse"];
                };
            };
        };
    };
    issueRealtimeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RealtimeSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RealtimeSessionResponse"];
                };
            };
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceOnlineBidRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OnlineAuctionResponse"];
                };
            };
        };
    };
}
export enum BidderRegistrationResponseApprovalStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED"
}
export enum BidderRegistrationResponseKycStatus {
    PENDING = "PENDING",
    PASSED = "PASSED",
    FAILED = "FAILED"
}
export enum BidderRegistrationResponseAccountCheckStatus {
    PENDING = "PENDING",
    PASSED = "PASSED",
    FAILED = "FAILED"
}
export enum OnlineAuctionResponseStatus {
    DRAFT = "DRAFT",
    PUBLISHED = "PUBLISHED",
    LIVE = "LIVE",
    CLOSED = "CLOSED"
}
