/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/tenants/{tenantId}/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAuctions"];
        put?: never;
        post: operations["createAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/auctions/{auctionId}/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["openAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/auctions/{auctionId}/lots/{lotId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["settleLot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/auctions/{auctionId}/lots/{lotId}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["placeBid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/auctions/{auctionId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["closeAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/auctions/{auctionId}/announce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["announceAuction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/surplus-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSurplusCases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuctionLotRequest: {
            contractNumber: string;
            itemNumber: string;
            description: string;
            estimatedValue: number;
            outstandingClaim: number;
        };
        CreateAuctionRequest: {
            title: string;
            location: string;
            lots?: components["schemas"]["AuctionLotRequest"][];
        };
        AuctionLotResponse: {
            id: string;
            /** Format: int32 */
            lotNumber: number;
            contractNumber: string;
            itemNumber: string;
            description: string;
            estimatedValue: number;
            outstandingClaim: number;
            latestBidAmount: number;
            leadingBidder: string;
            hammerPrice: number;
            /** @enum {string} */
            status: AuctionLotResponseStatus;
            surplusAmount: number;
            /** Format: date */
            authorityTransferDueDate: string;
            authorityTransferStatus: string;
        };
        AuctionResponse: {
            id: string;
            title: string;
            location: string;
            /** @enum {string} */
            status: AuctionResponseStatus;
            /** Format: date */
            publicAnnouncementDate: string;
            /** Format: date */
            auctionDate: string;
            /** Format: date-time */
            liveStartedAt: string;
            /** Format: date-time */
            closedAt: string;
            announcementReference: string;
            lots: components["schemas"]["AuctionLotResponse"][];
        };
        AuctionSettlementRequest: {
            hammerPrice: number;
        };
        PlaceBidRequest: {
            bidderDisplayName: string;
            amount: number;
        };
        AuctionStatusUpdateRequest: {
            /** Format: date */
            auctionDate?: string;
            announcementReference: string;
        };
        SurplusCaseResponse: {
            auctionId: string;
            lotId: string;
            /** Format: int32 */
            lotNumber: number;
            contractNumber: string;
            hammerPrice: number;
            outstandingClaim: number;
            surplusAmount: number;
            /** Format: date */
            authorityTransferDueDate: string;
            authorityTransferStatus: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAuctions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"][];
                };
            };
        };
    };
    createAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAuctionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"];
                };
            };
        };
    };
    openAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"];
                };
            };
        };
    };
    settleLot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
                lotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionSettlementRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"];
                };
            };
        };
    };
    placeBid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
                lotId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaceBidRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"];
                };
            };
        };
    };
    closeAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"];
                };
            };
        };
    };
    announceAuction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                auctionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuctionStatusUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuctionResponse"];
                };
            };
        };
    };
    listSurplusCases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SurplusCaseResponse"][];
                };
            };
        };
    };
}
export enum AuctionLotResponseStatus {
    PENDING = "PENDING",
    OPEN = "OPEN",
    SOLD = "SOLD",
    UNSOLD = "UNSOLD"
}
export enum AuctionResponseStatus {
    DRAFT = "DRAFT",
    ANNOUNCED = "ANNOUNCED",
    LIVE = "LIVE",
    CLOSED = "CLOSED",
    SETTLED = "SETTLED"
}
