/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pawn-tickets/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["redeem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/partial-repayment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["partialRepayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cash-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["execute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/pawn-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/{tenantId}/cash-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/{ticketNumber}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["labels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/{ticketNumber}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["document"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pawn-tickets/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/v1/customers/{tenantId}/{customerId}/pawn-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listCustomerTickets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/v1/customers/{tenantId}/{customerId}/pawn-tickets/{ticketNumber}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["document_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RedeemPawnTicketRequest: {
            tenantId: string;
            outstandingLoanAmount: number;
            /** Format: int32 */
            remainingTermMonths?: number;
            manualMonthlyOperatingFee?: number;
        };
        SettlementResponse: {
            outstandingLoanAmount: number;
            interestAmount: number;
            operatingFeeAmount: number;
            totalDueAmount: number;
            legalText: string;
        };
        PawnTicketQuoteRequest: {
            tenantId: string;
            loanAmount: number;
            /** Format: int32 */
            termMonths?: number;
            manualMonthlyOperatingFee?: number;
        };
        PawnTicketPositionResponse: {
            itemNumber: string;
            itemBarcode: string;
            label: string;
            description: string;
            pledgedValue: number;
        };
        PawnTicketResponse: {
            contractNumber: string;
            contractBarcode: string;
            ticketNumber: string;
            termsVersion: string;
            termsAndConditionsText: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date */
            dueDate: string;
            /** Format: date */
            earliestAuctionDate: string;
            /** Format: int32 */
            termMonths: number;
            totalLoanValue: number;
            monthlyInterestRate: number;
            monthlyOperatingFee: number;
            manualMonthlyOperatingFeeRequired: boolean;
            totalInterestAmount: number;
            totalOperatingFeeAmount: number;
            totalRepaymentAmount: number;
            legalText: string;
            positions: components["schemas"]["PawnTicketPositionResponse"][];
        };
        PartialRepaymentRequest: {
            tenantId: string;
            outstandingLoanAmount: number;
            repaymentAmount: number;
            /** Format: int32 */
            remainingTermMonths?: number;
            manualMonthlyOperatingFee?: number;
        };
        IssuePawnTicketRequest: {
            tenantId: string;
            customerId: string;
            customerNumber: string;
            customerDisplayName: string;
            customerPhone?: string;
            loanAmount: number;
            /** Format: int32 */
            termMonths?: number;
            manualMonthlyOperatingFee?: number;
            positions?: components["schemas"]["PawnTicketPositionPayload"][];
        };
        PawnTicketPositionPayload: {
            label: string;
            description: string;
            pledgedValue: number;
        };
        ExtendPawnTicketRequest: {
            tenantId: string;
            outstandingLoanAmount: number;
            /** Format: int32 */
            extensionMonths?: number;
            manualMonthlyOperatingFee?: number;
        };
        ExecuteCashTransactionRequest: {
            tenantId: string;
            ticketNumber: string;
            /** @enum {string} */
            type: ExecuteCashTransactionRequestType;
            outstandingLoanAmount: number;
            /** Format: int32 */
            extensionMonths?: number;
            repaymentAmount?: number;
            /** Format: int32 */
            remainingTermMonths?: number;
            manualMonthlyOperatingFee?: number;
            note?: string;
        };
        CashTransactionResponse: {
            id: string;
            ticketNumber: string;
            customerNumber: string;
            customerDisplayName: string;
            /** @enum {string} */
            type: CashTransactionResponseType;
            outstandingLoanAmount: number;
            interestAmount: number;
            operatingFeeAmount: number;
            totalAmount: number;
            legalText: string;
            note: string;
            /** Format: date-time */
            createdAt: string;
        };
        PawnTicketOverviewResponse: {
            contractNumber: string;
            ticketNumber: string;
            contractBarcode: string;
            termsVersion: string;
            customerNumber: string;
            customerDisplayName: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date */
            dueDate: string;
            /** Format: date */
            earliestAuctionDate: string;
            totalLoanValue: number;
            totalRepaymentAmount: number;
            /** Format: int32 */
            positionCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    redeem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RedeemPawnTicketRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettlementResponse"];
                };
            };
        };
    };
    quote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PawnTicketQuoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PawnTicketResponse"];
                };
            };
        };
    };
    partialRepayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartialRepaymentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SettlementResponse"];
                };
            };
        };
    };
    issue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuePawnTicketRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PawnTicketResponse"];
                };
            };
        };
    };
    extend: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtendPawnTicketRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PawnTicketResponse"];
                };
            };
        };
    };
    execute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecuteCashTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashTransactionResponse"];
                };
            };
        };
    };
    listTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PawnTicketOverviewResponse"][];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CashTransactionResponse"][];
                };
            };
        };
    };
    labels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    document: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticketNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    listCustomerTickets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PawnTicketOverviewResponse"][];
                };
            };
        };
    };
    document_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenantId: string;
                customerId: string;
                ticketNumber: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
}
export enum ExecuteCashTransactionRequestType {
    REDEEM = "REDEEM",
    EXTEND = "EXTEND",
    PARTIAL_REPAYMENT = "PARTIAL_REPAYMENT"
}
export enum CashTransactionResponseType {
    REDEEM = "REDEEM",
    EXTEND = "EXTEND",
    PARTIAL_REPAYMENT = "PARTIAL_REPAYMENT"
}
